name: shorkariiq
description: "An adaptive learning quiz app"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_markdown: ^0.6.14
  path_provider: ^2.1.2

  flutter_local_notifications: ^17.2.1
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  timezone: ^0.9.4
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/questions.json
    - assets/user_progress.json
    - assets/ShorkariIQLogo.png


icons_launcher:
  image_path: "assets/ShorkariIQLogo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/ShorkariIQLogo.png"
      adaptive_foreground_image: "assets/ShorkariIQLogo.png"
    windows:
      enable: true
      image_path: "assets/ShorkariIQLogo.png"
flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
  image_path: "assets/ShorkariIQLogo.png"
